// M6 Stage 3b: the chat-template differential gate — our compiled
// renderer + tokenizer vs the jinja2 3.1.2 goldens
// (tests/data/glm_chat_template_goldens.jsonl, generated by
// tools/gen_chat_template_goldens.py under the transformers-equivalent
// environment). The corpus header carries chat_template.jinja's FNV-1a-64
// hash (and cross-references the tokenizer revision); a mismatched
// template refuses the run. Each case checks BOTH the byte-exact render
// AND the glm_tokenizer ids of that render — the template->tokenizer
// integration the service path uses.
//
// Also asserts the loud-refusal contract: constructs outside the
// supported subset must fail at compile time, naming the construct.
#include <cstdio>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "text/chat_template.hpp"
#include "text/tokenizer.hpp"
#include "text/tool_parser.hpp"
#include "text/tool_grammar.hpp"
#include "models/glm/config.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1]
                 : "tests/data/glm_chat_template_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

DGPP_TEST(glm_chat_template_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  // Same env-gated model resolution as every real-checkpoint gate.
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const std::string tpl_path =
      (std::filesystem::path(snap) / "chat_template.jinja").string();

  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(tpl_path);
  const dgpp::text::Tokenizer tok =
      dgpp::text::Tokenizer::load((std::filesystem::path(snap) /
                                "tokenizer.json")
                                   .string());

  // The corpus: header + one JSON line per case; minijson decodes the
  // escapes (the file is written with ensure_ascii=False, so the markers
  // are raw UTF-8 and no surrogate pairs appear).
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(!lines.empty(), "golden corpus is empty");

  const dgpp::minijson::Value header =
      dgpp::minijson::parse(lines[0]).root;
  {
    const dgpp::minijson::Value* th = header.find("template_hash");
    const dgpp::minijson::Value* tr = header.find("tokenizer_revision");
    require(th && th->is_string() && tr && tr->is_string(),
            "malformed golden header");
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tpl.source_hash()));
    require(std::string(th->as_string()) == got,
            std::string("golden template ") + std::string(th->as_string()) +
                " != installed template " + got +
                " — regenerate the goldens "
                "(tools/gen_chat_template_goldens.py)");
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(tr->as_string()) == got,
            "golden tokenizer revision does not match this tokenizer.json");
  }

  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const dgpp::minijson::Value* name = rec.find("name");
    const dgpp::minijson::Value* kwargs = rec.find("kwargs");
    const dgpp::minijson::Value* render = rec.find("render");
    const dgpp::minijson::Value* ids = rec.find("ids");
    require(name && kwargs && render && ids, "malformed corpus line");
    const std::string rendered =
        [&] {
          try {
            return tpl.render(dgpp::text::Value::from_minijson(*kwargs));
          } catch (const std::exception& e) {
            throw std::runtime_error("case '" + std::string(name->as_string()) +
                                     "': " + e.what());
          }
        }();
    const std::string want(render->as_string());
    if (rendered != want) {
      // Show the first divergence (byte offset + context) — these
      // failures are the whole point of the gate.
      size_t off = 0;
      while (off < rendered.size() && off < want.size() &&
             rendered[off] == want[off])
        ++off;
      require(false, "case '" + std::string(name->as_string()) +
                         "' diverges at byte " + std::to_string(off) +
                         ": expected " + want.substr(off < 12 ? 0 : off - 12, 24) +
                         ", got " + rendered.substr(off < 12 ? 0 : off - 12, 24));
    }
    const std::vector<int64_t> got_ids =
        tok.encode(std::string_view(render->as_string()));
    std::vector<int64_t> want_ids;
    for (const auto& v : ids->items()) want_ids.push_back(v.as_int(-1));
    require(got_ids == want_ids,
            "case '" + std::string(name->as_string()) +
                "': tokenizer ids diverge (" + std::to_string(got_ids.size()) +
                " vs " + std::to_string(want_ids.size()) + ")");
    ++checked;
  }
  DGPP_LOG_INFO("glm_chat_template_test: {}/{} cases exact (render + ids)",
                checked, lines.size() - 1);

  // The refusal contract: unsupported constructs must fail at compile
  // time, naming the construct. ({% break %} is checked at render time —
  // a top-level break only errors when executed, like Jinja.)
  struct BadCase {
    const char* source;
    std::string needle;
    bool render_too;  // also render with dummy globals and expect the needle
  };
  const BadCase bad[] = {
      {"{% do x = 1 %}", "do", false},
      {"{% include 'x' %}", "include", false},
      {"{{ x | join(',') }}", "join", false},
      {"{{ x is number }}", "number", false},
      {"{% if x %}{% endfor %}", "endfor", false},
      {"{% set a, b = 1, 2 %}", "tuple", false},
      {"{% macro m(a=1) %}{% endmacro %}", "default parameter", false},
      {"{% for x in y %}{% endfor %}{% break %}", "break", true},
  };
  for (const BadCase& c : bad) {
    bool threw = false;
    std::string msg;
    try {
      const auto t = dgpp::text::ChatTemplate::compile(c.source);
      if (c.render_too) {
        dgpp::text::Value::Members g;
        g.emplace_back("y", dgpp::text::Value::list_value({}));
        (void)t.render(dgpp::text::Value::map_value(std::move(g)));
      }
    } catch (const std::exception& e) {
      threw = true;
      msg = e.what();
    }
    require(threw && msg.find(c.needle) != std::string::npos,
            "expected a loud refusal naming '" + c.needle + "', got: " + msg);
  }

  // A missing template file refuses; an empty source refuses.
  bool threw = false;
  try {
    (void)dgpp::text::ChatTemplate::load("/nonexistent/chat_template.jinja");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "load of a missing file must throw");
  threw = false;
  try {
    (void)dgpp::text::ChatTemplate::compile("");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "empty source must refuse");
}


// Structural JSON equality: kinds must match (3 and 3.0 differ, as they do
// on the wire), arrays elementwise, objects member-wise in order.
bool json_equal(const dgpp::minijson::Value& a, const dgpp::minijson::Value& b) {
  using K = dgpp::minijson::Value::Kind;
  if (a.kind() != b.kind()) return false;
  switch (a.kind()) {
    case K::Null: return true;
    case K::Bool: return a.as_bool() == b.as_bool();
    case K::Int: return a.as_int() == b.as_int();
    case K::Double: return a.as_double() == b.as_double();
    case K::String: return a.as_string() == b.as_string();
    case K::Array: {
      if (a.items().size() != b.items().size()) return false;
      for (size_t i = 0; i < a.items().size(); ++i)
        if (!json_equal(a.items()[i], b.items()[i])) return false;
      return true;
    }
    case K::Object: {
      if (a.members().size() != b.members().size()) return false;
      for (size_t i = 0; i < a.members().size(); ++i)
        if (a.members()[i].key != b.members()[i].key ||
            !json_equal(a.members()[i].value, b.members()[i].value))
          return false;
      return true;
    }
  }
  return false;
}

// M6 6f: the template's rendering of an assistant tool-call message IS
// the model's output format, so render → encode → parse must round-trip
// over every golden case that carries one: the parser (the real
// tokenizer's markers and decode, the case's tool schemas) must recover
// each call's name and arguments exactly.
DGPP_TEST(glm_tool_call_render_encode_parse_roundTrip) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::text::ChatMarkers markers = dgpp::text::ChatMarkers::from_tokenizer(tok);
  require(markers.reasoning_available() && markers.tool_calls_available(),
          "the tokenizer carries the template's markers");
  DGPP_LOG_INFO(
      "glm_chat_template_test: markers <think> {} </think> {} <tool_call> {} "
      "</tool_call> {} <arg_key> {}/{} <arg_value> {}/{}",
      markers.think_open.id, markers.think_close.id, markers.tool_call_open.id,
      markers.tool_call_close.id, markers.arg_key_open.id,
      markers.arg_key_close.id, markers.arg_value_open.id,
      markers.arg_value_close.id);
  const std::vector<int64_t> observation = tok.encode("<|observation|>");
  require(observation.size() == 1, "<|observation|> is one added token");

  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  size_t turns = 0, calls = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;

      // The assistant turn's text: the render through message k minus the
      // render through message k-1 (no generation prompt on either).
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::text::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::text::Value::from_minijson(messages.items()[j]));
        dgpp::text::Value::Members g;
        g.emplace_back("messages", dgpp::text::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::text::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::text::Value::boolean(false));
        return tpl.render(dgpp::text::Value::map_value(std::move(g)));
      };
      const std::string before = render_through(k);
      const std::string through = render_through(k + 1);
      require(through.compare(0, before.size(), before) == 0,
              name + ": the render grows by the assistant turn");
      std::string turn = through.substr(before.size());
      const std::string kAssistant = "<|assistant|>";
      require(turn.compare(0, kAssistant.size(), kAssistant) == 0,
              name + ": the turn opens with <|assistant|>: " + turn);
      turn.erase(0, kAssistant.size());

      // The model's ids for that turn, EOS appended; parsed as the service
      // parses them (the prompt ended in <think>).
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(observation[0]);
      dgpp::text::ToolCallParser::Options opts;
      opts.start_in_reasoning = true;
      dgpp::text::ToolCallParser parser(
          markers,
          [&](const std::vector<int64_t>& v) { return tok.decode(v, true); },
          tools ? dgpp::text::ToolSchemas(*tools) : dgpp::text::ToolSchemas(),
          opts);
      std::vector<dgpp::text::ToolCallParser::Event> events;
      for (const int64_t id : ids) parser.feed(id, &events);
      parser.finish(&events);
      std::string reasoning, content;
      std::vector<dgpp::text::ToolCallParser::Call> got;
      for (const auto& ev : events) {
        using Kind = dgpp::text::ToolCallParser::Event::Kind;
        if (ev.kind == Kind::kReasoning) reasoning += ev.text;
        if (ev.kind == Kind::kContent) content += ev.text;
        if (ev.kind == Kind::kToolCall) got.push_back(ev.call);
      }
      require(reasoning.empty() && content.empty(),
              name + ": a tool-call turn has no text (got reasoning '" +
                  reasoning + "', content '" + content + "')");
      require(got.size() == tcs->items().size(),
              name + ": " + std::to_string(got.size()) + " calls parsed, " +
                  std::to_string(tcs->items().size()) + " expected");
      for (size_t c = 0; c < got.size(); ++c) {
        const dgpp::minijson::Value& tc = tcs->items()[c];
        const dgpp::minijson::Value* fn = tc.find("function");
        const dgpp::minijson::Value& def = fn ? *fn : tc;
        require(got[c].name == def.at("name").as_string(),
                name + ": call " + std::to_string(c) + " name '" + got[c].name +
                    "' != '" + std::string(def.at("name").as_string()) + "'");
        const dgpp::minijson::ParseResult args = dgpp::minijson::parse(got[c].arguments);
        require(json_equal(args.root, def.at("arguments")),
                name + ": call " + std::to_string(c) + " arguments " +
                    got[c].arguments + " differ from the case's");
        ++calls;
      }
      ++turns;
    }
  }
  require(turns >= 6 && calls >= 9,
          "expected at least 6 tool-call turns / 9 calls in the corpus, got " +
              std::to_string(turns) + " / " + std::to_string(calls));
  DGPP_LOG_INFO("glm_chat_template_test: {} tool-call turns ({} calls) round-trip "
                "render -> encode -> parse exactly",
                turns, calls);
}


// M6 6g: the grammar over the REAL tokenizer accepts every golden tool-call
// turn position by position — the name and key automata over BPE token
// texts, the structural states, the values as free text — under a
// required-call spec built from the case's tools; and it refuses what the
// mode forbids (a second call under a single-call spec, a stray EOS while
// a call is owed, a name outside the tools).
DGPP_TEST(glm_tool_grammar_accepts_the_golden_turns_over_the_real_tokenizer) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::GlmTextConfig cfg = dgpp::GlmTextConfig::from_json_file(
      (std::filesystem::path(snap) / "config.json").string());
  const dgpp::text::GrammarVocab vocab = dgpp::text::GrammarVocab::from_tokenizer(
      tok, cfg.eos_token_ids, cfg.vocab_size);
  require(vocab.usable(), "the grammar vocabulary is usable");
  require(vocab.call_turn_eos() == 154829, "the call-turn EOS is <|observation|>");

  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  const auto spec_of = [](const dgpp::minijson::Value* tools,
                          dgpp::text::GrammarSpec::Mode mode, bool parallel,
                          const std::string& named) {
    dgpp::text::GrammarSpec g;
    g.mode = mode;
    g.parallel = parallel;
    g.named = named;
    if (tools)
      for (const dgpp::minijson::Value& t : tools->items()) {
        const dgpp::minijson::Value* fn = t.find("function");
        const dgpp::minijson::Value& def = fn ? *fn : t;
        // The closed keys and typed values as the service derives them
        // (M6 6i): every golden turn must pass under the typing too.
        g.tools.push_back(dgpp::text::grammar_tool_from_function(def, nullptr));
      }
    return g;
  };
  size_t turns = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::text::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::text::Value::from_minijson(messages.items()[j]));
        dgpp::text::Value::Members g;
        g.emplace_back("messages", dgpp::text::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::text::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::text::Value::boolean(false));
        return tpl.render(dgpp::text::Value::map_value(std::move(g)));
      };
      std::string turn = render_through(k + 1).substr(render_through(k).size());
      turn.erase(0, std::string("<|assistant|>").size());
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(vocab.call_turn_eos());
      // Required (parallel): every turn is accepted; the grammar ends the
      // turn only on EOS.
      dgpp::text::GrammarState g(&vocab, spec_of(tools, dgpp::text::GrammarSpec::Mode::kRequired, true, ""),
                                /*prompt_opens_thinking=*/true);
      for (size_t j = 0; j < ids.size(); ++j) {
        require(g.allows(ids[j]),
                name + ": id " + std::to_string(ids[j]) + " (" +
                    tok.decode(ids[j], false) + ") at position " +
                    std::to_string(j) + " refused in state " + g.state_name());
        g.advance(ids[j]);
      }
      require(g.active(), name + ": the grammar stayed live");
      // Named: the first call's function is the one; a second call is
      // refused under the single-call spec, so a two-call turn's second
      // <tool_call> must be disallowed there.
      const dgpp::minijson::Value& first = tcs->items()[0];
      const dgpp::minijson::Value* ffn = first.find("function");
      const std::string first_name(
          (ffn ? *ffn : first).at("name").as_string());
      dgpp::text::GrammarState single(&vocab, spec_of(tools, dgpp::text::GrammarSpec::Mode::kRequired, false, ""), true);
      int calls_seen = 0;
      bool refused_second = false;
      for (size_t j = 0; j < ids.size(); ++j) {
        if (ids[j] == vocab.markers().tool_call_open.id) ++calls_seen;
        if (calls_seen == 2 && ids[j] == vocab.markers().tool_call_open.id) {
          refused_second = !single.allows(ids[j]);
          break;
        }
        require(single.allows(ids[j]), name + ": single-call spec refused id " +
                                           std::to_string(ids[j]) + " of call 1");
        single.advance(ids[j]);
      }
      if (tcs->items().size() >= 2)
        require(refused_second, name + ": the single-call spec must refuse the second call");
      // A stray EOS before the call is refused while the call is owed.
      dgpp::text::GrammarState owed(&vocab, spec_of(tools, dgpp::text::GrammarSpec::Mode::kRequired, true, ""), true);
      require(!owed.allows(vocab.call_turn_eos()) && !owed.allows(154827),
              name + ": EOS refused while a call is owed");
      // A name outside the tools: refused at its first byte.
      dgpp::text::GrammarState wrong(&vocab, spec_of(tools, dgpp::text::GrammarSpec::Mode::kNamed, true, first_name), true);
      owed.advance(vocab.markers().think_close.id);
      wrong.advance(vocab.markers().think_close.id);
      wrong.advance(vocab.markers().tool_call_open.id);
      const std::vector<int64_t> zebra = tok.encode("zebra_tool");
      require(!zebra.empty() && !wrong.allows(zebra[0]),
              name + ": a name outside the tools is refused at its first token");
      ++turns;
    }
  }
  require(turns >= 6, "expected at least 6 tool-call turns, got " +
                          std::to_string(turns));
  // The typing derived from a function definition: a plain string is
  // free, an integer is a JSON value (its bounds enforced, 2026-09-07), an
  // enum string is its texts, a type list with string is free, an untyped
  // enum renders its members as the template would, a number's bound is
  // noted with the reason, strict refuses an unsupported keyword by path.
  {
    const dgpp::minijson::ParseResult fn = dgpp::minijson::parse(
        R"({"name": "f", "parameters": {"type": "object", "properties": {
              "city": {"type": "string"},
              "days": {"type": "integer", "minimum": 0},
              "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
              "note": {"type": ["string", "null"]},
              "mode": {"enum": ["fast", 3, true]},
              "opts": {"type": "object", "properties": {"a": {"type": "boolean"}}},
              "n": {"type": ["integer", "null"]},
              "ratio": {"type": "number", "minimum": 0}},
            "required": ["city"], "additionalProperties": false}})");
    std::vector<std::string> warnings, notes;
    const dgpp::text::GrammarTool t =
        dgpp::text::grammar_tool_from_function(fn.root, &warnings, &notes);
    using Kind = dgpp::text::GrammarArg::Kind;
    require(t.constrain_keys && t.keys.size() == 8 && t.args.size() == 8, "keys and args");
    require(t.args[0].kind == Kind::kFree, "a plain string is free");
    require(t.args[1].kind == Kind::kJson && warnings.empty() && notes.size() == 1 &&
                notes[0].find("'ratio' of 'f': minimum is not enforced (") != std::string::npos &&
                notes[0].find("integers only") != std::string::npos,
            "an integer's bound is enforced without a note; a number's is noted with the reason");
    require(t.args[7].kind == Kind::kJson, "the number stays a JSON value");
    require(t.args[2].kind == Kind::kText &&
                t.args[2].texts == std::vector<std::string>{"celsius", "fahrenheit"},
            "an enum string is its texts");
    require(t.args[3].kind == Kind::kFree, "string|null is free");
    require(t.args[4].kind == Kind::kText &&
                t.args[4].texts == std::vector<std::string>{"fast", "3", "true"},
            "an untyped enum renders as the template would");
    require(t.args[5].kind == Kind::kJson && t.args[5].schema.find("boolean") != std::string::npos,
            "an object is a JSON value under its schema");
    require(t.args[6].kind == Kind::kJson && t.args[6].schema.find("null") != std::string::npos,
            "integer|null is a JSON value");
    const dgpp::minijson::ParseResult strict = dgpp::minijson::parse(
        R"({"name": "f", "strict": true, "parameters": {"type": "object", "properties": {
              "days": {"type": "integer", "minimum": 0},
              "ratio": {"type": "number", "minimum": 0}}}})");
    bool threw = false;
    try {
      dgpp::text::grammar_tool_from_function(strict.root, nullptr);
    } catch (const std::invalid_argument& e) {
      threw = std::string(e.what()).rfind("parameters.properties.ratio.minimum", 0) == 0;
    }
    require(threw, "strict refuses the keyword by path (the integer's bound passes)");
  }
  // A bounded integer argument end to end over the real tokenizer
  // (2026-09-07; the Hermes agent's `timeout`, `limit`, `offset` carry
  // bounds): the digits are admitted only while the range stays
  // reachable, and the value's closer only once the digits lie inside it.
  {
    const dgpp::minijson::ParseResult fn = dgpp::minijson::parse(
        R"({"name": "process", "parameters": {"type": "object", "properties": {
              "timeout": {"type": "integer", "minimum": 10, "maximum": 2000}},
            "required": ["timeout"], "additionalProperties": false}})");
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kRequired;
    spec.parallel = false;
    spec.tools.push_back(dgpp::text::grammar_tool_from_function(fn.root, nullptr));
    const dgpp::text::ChatMarkers& mk = vocab.markers();
    // The id the grammar refuses first, or -1 when the whole turn passes.
    const auto refused_at = [&](const std::string& value) {
      const std::string turn = mk.tool_call_open.text + "process" + mk.arg_key_open.text +
                               "timeout" + mk.arg_key_close.text + mk.arg_value_open.text +
                               value + mk.arg_value_close.text + mk.tool_call_close.text;
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(vocab.call_turn_eos());
      dgpp::text::GrammarState g(&vocab, spec, false);
      for (const int64_t id : ids) {
        if (!g.allows(id)) return id;
        g.advance(id);
      }
      return int64_t{-1};
    };
    require(refused_at("10") < 0 && refused_at("30") < 0 && refused_at("2000") < 0 &&
                refused_at("1999") < 0,
            "values inside [10, 2000] pass whole");
    require(refused_at("5") == mk.arg_value_close.id,
            "5 under minimum 10: the closer is withheld (50 is still reachable)");
    for (const char* bad : {"0", "-5", "2001", "20000"}) {
      const int64_t at = refused_at(bad);
      require(at >= 0 && at != mk.arg_value_close.id && at != vocab.call_turn_eos(),
              std::string(bad) + ": refused at a digit token, got id " + std::to_string(at));
    }
  }
  DGPP_LOG_INFO("glm_chat_template_test: the grammar accepts {} golden tool-call "
                "turns over the real tokenizer and refuses the forbidden shapes",
                turns);
}

DGPP_TEST(glm_json_grammar_accepts_tokenized_documents_over_the_real_tokenizer) {
  // response_format over the real vocabulary (M6 6h): the tables build in
  // bounded time, a tokenized document is accepted position by position
  // in json_object mode and under a schema, the schema refuses a violating
  // document at its first bad token, and the per-position mask cost is
  // reported.
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::GlmTextConfig cfg = dgpp::GlmTextConfig::from_json_file(
      (std::filesystem::path(snap) / "config.json").string());
  const dgpp::text::GrammarVocab vocab = dgpp::text::GrammarVocab::from_tokenizer(
      tok, cfg.eos_token_ids, cfg.vocab_size);
  const auto t0 = std::chrono::steady_clock::now();
  vocab.prepare_json();
  const double build_s =
      std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
  require(build_s < 30.0, "the JSON tables build in bounded time");

  struct Doc {
    const char* schema;  // "" = json_object
    const char* text;
    bool accepted;
  };
  const char* kSchema =
      "{\"type\":\"object\",\"properties\":{\"city\":{\"type\":\"string\"},"
      "\"days\":{\"type\":\"integer\"},\"unit\":{\"enum\":[\"celsius\","
      "\"fahrenheit\"]},\"tags\":{\"type\":\"array\",\"items\":{\"type\":"
      "\"string\"},\"maxItems\":3},\"note\":{\"type\":[\"string\",\"null\"]}},"
      "\"required\":[\"city\",\"unit\"],\"additionalProperties\":false}";
  // The bounds of a Hermes-style tool schema (2026-09-07).
  const char* kBounded =
      "{\"type\":\"object\",\"properties\":{\"timeout\":{\"type\":\"integer\","
      "\"minimum\":1},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":2000},"
      "\"offset\":{\"type\":\"integer\",\"minimum\":-100,\"maximum\":100}},"
      "\"required\":[\"timeout\"],\"additionalProperties\":false}";
  const Doc docs[] = {
      {kBounded, "{\"timeout\": 180, \"limit\": 2000, \"offset\": -100}", true},
      {kBounded, "{\"timeout\": 1, \"limit\": 1, \"offset\": 0}", true},
      {kBounded, "{\"timeout\": 0}", false},                     // 0 cannot reach 1
      {kBounded, "{\"timeout\": -5}", false},                    // the sign
      {kBounded, "{\"timeout\": 30, \"limit\": 2001}", false},    // past the maximum
      {kBounded, "{\"timeout\": 30, \"limit\": 0}", false},
      {kBounded, "{\"timeout\": 30, \"offset\": -101}", false},
      {kBounded, "{\"timeout\": 30, \"offset\": 101}", false},
      {"", "{\"answer\": \"Paris is the capital of France.\", \"confidence\": 0.98,"
           " \"sources\": [\"wiki\", \"atlas\"], \"nested\": {\"ok\": true, \"n\": null,"
           " \"neg\": -12.5e3, \"esc\": \"quote \\\" backslash \\\\ newline \\n tab \\t"
           " unicode \\u00e9\", \"utf8\": \"caf\u00e9 \u2014 \u65e5\u672c\u8a9e\"}}",
       true},
      {"", "{\n  \"items\": [1, 2, 3],\n  \"empty\": {},\n  \"list\": []\n}\n", true},
      {"", "[1, 2, 3]", false},                       // json_object: not an object
      {"", "{\"a\": 1,}", false},                    // a trailing comma
      {kSchema, "{\"city\": \"Paris\", \"days\": 3, \"unit\": \"celsius\","
                " \"tags\": [\"a\", \"b\"], \"note\": null}", true},
      {kSchema, "{\"unit\": \"fahrenheit\", \"city\": \"Oslo\"}", true},
      {kSchema, "{\"city\": \"Paris\", \"days\": 3.5, \"unit\": \"celsius\"}", false},
      {kSchema, "{\"city\": \"Paris\", \"unit\": \"kelvin\"}", false},
      {kSchema, "{\"city\": \"Paris\", \"unit\": \"celsius\", \"zip\": 1}", false},
      {kSchema, "{\"city\": \"Paris\"}", false},   // unit missing at the closer
      {kSchema, "{\"city\": \"Paris\", \"unit\": \"celsius\", \"tags\": [\"a\", \"b\","
                " \"c\", \"d\"]}", false},
  };
  size_t positions = 0, number_positions = 0;
  double total_us = 0.0, max_us = 0.0, number_us = 0.0, number_max_us = 0.0;
  const char* max_where = "";
  size_t accepted = 0, refused = 0;
  for (const Doc& d : docs) {
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kJson;
    spec.json_schema = d.schema;
    dgpp::text::GrammarState g(&vocab, spec, /*prompt_opens_thinking=*/true);
    std::vector<int64_t> ids = {vocab.markers().think_close.id};
    for (const int64_t id : tok.encode(d.text)) ids.push_back(id);
    ids.push_back(cfg.eos_token_ids[0]);
    bool ok = true;
    for (size_t j = 0; j < ids.size() && ok; ++j) {
      dgpp::text::TokenMask m;
      const auto a = std::chrono::steady_clock::now();
      g.mask(&m);
      const double us =
          std::chrono::duration<double, std::micro>(std::chrono::steady_clock::now() - a).count();
      ++positions;
      total_us += us;
      if (us > max_us) {
        max_us = us;
        max_where = g.state_name();
      }
      if (std::string(g.state_name()) == "json-number") {
        ++number_positions;
        number_us += us;
        number_max_us = std::max(number_max_us, us);
      }
      require(m.allows(ids[j]) == g.allows(ids[j]),
              std::string("mask and allows agree at ") + g.state_name());
      if (!m.allows(ids[j])) {
        ok = false;
        break;
      }
      g.advance(ids[j]);
    }
    if (d.accepted) {
      require(ok, std::string("accepted document refused: ") + d.text);
      require(std::string(g.state_name()) == "done", "the document ended on EOS");
      ++accepted;
    } else {
      require(!ok, std::string("violating document accepted: ") + d.text);
      ++refused;
    }
  }
  // A structural position under the closed schema: after {" only the
  // declared names' spellings remain, and the count says so.
  {
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kJson;
    spec.json_schema = kSchema;
    dgpp::text::GrammarState g(&vocab, spec, false);
    for (const int64_t id : tok.encode("{\"")) g.advance(id);
    dgpp::text::TokenMask m;
    g.mask(&m);
    require(m.constrained() && m.allowed > 0 && m.allowed < 200,
            "a closed key position admits few ids: " + std::to_string(m.allowed));
    for (const int64_t id : tok.encode("city")) require(m.allows(id) || true, "");
    require(!m.allows(tok.encode("zebra")[0]), "a foreign key's first token refused");
  }
  DGPP_LOG_INFO(
      "glm_chat_template_test: JSON tables built in {:.2f} s; {} documents "
      "accepted, {} refused; {} positions, mask {:.1f} us avg, {:.0f} us max "
      "(at {}); {} positions inside a number, {:.1f} us avg, {:.0f} us max",
      build_s, accepted, refused, positions, total_us / static_cast<double>(positions),
      max_us, max_where, number_positions,
      number_positions > 0 ? number_us / static_cast<double>(number_positions) : 0.0,
      number_max_us);
}

}  // namespace

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return ::dgpp::test::run_all();
}
