// M6 Stage 3b: the chat-template differential gate — our compiled
// renderer + tokenizer vs the jinja2 3.1.2 goldens
// (tests/data/glm_chat_template_goldens.jsonl, generated by
// tools/gen_chat_template_goldens.py under the transformers-equivalent
// environment). The corpus header carries chat_template.jinja's FNV-1a-64
// hash (and cross-references the tokenizer revision); a mismatched
// template refuses the run. Each case checks BOTH the byte-exact render
// AND the glm_tokenizer ids of that render — the template->tokenizer
// integration the service path uses.
//
// Also asserts the loud-refusal contract: constructs outside the
// supported subset must fail at compile time, naming the construct.
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "models/glm_chat_template.hpp"
#include "models/glm_tokenizer.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1]
                 : "tests/data/glm_chat_template_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

DGPP_TEST(glm_chat_template_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  // Same env-gated model resolution as every real-checkpoint gate.
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const std::string tpl_path =
      (std::filesystem::path(snap) / "chat_template.jinja").string();

  const dgpp::glm::ChatTemplate tpl = dgpp::glm::ChatTemplate::load(tpl_path);
  const dgpp::GlmTokenizer tok =
      dgpp::GlmTokenizer::load((std::filesystem::path(snap) /
                                "tokenizer.json")
                                   .string());

  // The corpus: header + one JSON line per case; minijson decodes the
  // escapes (the file is written with ensure_ascii=False, so the markers
  // are raw UTF-8 and no surrogate pairs appear).
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(!lines.empty(), "golden corpus is empty");

  const dgpp::minijson::Value header =
      dgpp::minijson::parse(lines[0]).root;
  {
    const dgpp::minijson::Value* th = header.find("template_hash");
    const dgpp::minijson::Value* tr = header.find("tokenizer_revision");
    require(th && th->is_string() && tr && tr->is_string(),
            "malformed golden header");
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tpl.source_hash()));
    require(std::string(th->as_string()) == got,
            std::string("golden template ") + std::string(th->as_string()) +
                " != installed template " + got +
                " — regenerate the goldens "
                "(tools/gen_chat_template_goldens.py)");
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(tr->as_string()) == got,
            "golden tokenizer revision does not match this tokenizer.json");
  }

  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const dgpp::minijson::Value* name = rec.find("name");
    const dgpp::minijson::Value* kwargs = rec.find("kwargs");
    const dgpp::minijson::Value* render = rec.find("render");
    const dgpp::minijson::Value* ids = rec.find("ids");
    require(name && kwargs && render && ids, "malformed corpus line");
    const std::string rendered =
        [&] {
          try {
            return tpl.render(dgpp::glm::Value::from_minijson(*kwargs));
          } catch (const std::exception& e) {
            throw std::runtime_error("case '" + std::string(name->as_string()) +
                                     "': " + e.what());
          }
        }();
    const std::string want(render->as_string());
    if (rendered != want) {
      // Show the first divergence (byte offset + context) — these
      // failures are the whole point of the gate.
      size_t off = 0;
      while (off < rendered.size() && off < want.size() &&
             rendered[off] == want[off])
        ++off;
      require(false, "case '" + std::string(name->as_string()) +
                         "' diverges at byte " + std::to_string(off) +
                         ": expected " + want.substr(off < 12 ? 0 : off - 12, 24) +
                         ", got " + rendered.substr(off < 12 ? 0 : off - 12, 24));
    }
    const std::vector<int64_t> got_ids =
        tok.encode(std::string_view(render->as_string()));
    std::vector<int64_t> want_ids;
    for (const auto& v : ids->items()) want_ids.push_back(v.as_int(-1));
    require(got_ids == want_ids,
            "case '" + std::string(name->as_string()) +
                "': tokenizer ids diverge (" + std::to_string(got_ids.size()) +
                " vs " + std::to_string(want_ids.size()) + ")");
    ++checked;
  }
  DGPP_LOG_INFO("glm_chat_template_test: {}/{} cases exact (render + ids)",
                checked, lines.size() - 1);

  // The refusal contract: unsupported constructs must fail at compile
  // time, naming the construct. ({% break %} is checked at render time —
  // a top-level break only errors when executed, like Jinja.)
  struct BadCase {
    const char* source;
    std::string needle;
    bool render_too;  // also render with dummy globals and expect the needle
  };
  const BadCase bad[] = {
      {"{% do x = 1 %}", "do", false},
      {"{% include 'x' %}", "include", false},
      {"{{ x | join(',') }}", "join", false},
      {"{{ x is number }}", "number", false},
      {"{% if x %}{% endfor %}", "endfor", false},
      {"{% set a, b = 1, 2 %}", "tuple", false},
      {"{% macro m(a=1) %}{% endmacro %}", "default parameter", false},
      {"{% for x in y %}{% endfor %}{% break %}", "break", true},
  };
  for (const BadCase& c : bad) {
    bool threw = false;
    std::string msg;
    try {
      const auto t = dgpp::glm::ChatTemplate::compile(c.source);
      if (c.render_too) {
        dgpp::glm::Value::Members g;
        g.emplace_back("y", dgpp::glm::Value::list_value({}));
        (void)t.render(dgpp::glm::Value::map_value(std::move(g)));
      }
    } catch (const std::exception& e) {
      threw = true;
      msg = e.what();
    }
    require(threw && msg.find(c.needle) != std::string::npos,
            "expected a loud refusal naming '" + c.needle + "', got: " + msg);
  }

  // A missing template file refuses; an empty source refuses.
  bool threw = false;
  try {
    (void)dgpp::glm::ChatTemplate::load("/nonexistent/chat_template.jinja");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "load of a missing file must throw");
  threw = false;
  try {
    (void)dgpp::glm::ChatTemplate::compile("");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "empty source must refuse");
}

}  // namespace

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return ::dgpp::test::run_all();
}
