// M6 Stage 3b: the chat-template differential gate — our compiled
// renderer + tokenizer vs the jinja2 3.1.2 goldens
// (tests/data/glm_chat_template_goldens.jsonl, generated by
// tools/gen_chat_template_goldens.py under the transformers-equivalent
// environment). The corpus header carries chat_template.jinja's FNV-1a-64
// hash (and cross-references the tokenizer revision); a mismatched
// template refuses the run. Each case checks BOTH the byte-exact render
// AND the glm_tokenizer ids of that render — the template->tokenizer
// integration the service path uses.
//
// Also asserts the loud-refusal contract: constructs outside the
// supported subset must fail at compile time, naming the construct.
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "models/glm_chat_template.hpp"
#include "models/glm_tokenizer.hpp"
#include "models/glm_tool_parser.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1]
                 : "tests/data/glm_chat_template_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

DGPP_TEST(glm_chat_template_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  // Same env-gated model resolution as every real-checkpoint gate.
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const std::string tpl_path =
      (std::filesystem::path(snap) / "chat_template.jinja").string();

  const dgpp::glm::ChatTemplate tpl = dgpp::glm::ChatTemplate::load(tpl_path);
  const dgpp::GlmTokenizer tok =
      dgpp::GlmTokenizer::load((std::filesystem::path(snap) /
                                "tokenizer.json")
                                   .string());

  // The corpus: header + one JSON line per case; minijson decodes the
  // escapes (the file is written with ensure_ascii=False, so the markers
  // are raw UTF-8 and no surrogate pairs appear).
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(!lines.empty(), "golden corpus is empty");

  const dgpp::minijson::Value header =
      dgpp::minijson::parse(lines[0]).root;
  {
    const dgpp::minijson::Value* th = header.find("template_hash");
    const dgpp::minijson::Value* tr = header.find("tokenizer_revision");
    require(th && th->is_string() && tr && tr->is_string(),
            "malformed golden header");
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tpl.source_hash()));
    require(std::string(th->as_string()) == got,
            std::string("golden template ") + std::string(th->as_string()) +
                " != installed template " + got +
                " — regenerate the goldens "
                "(tools/gen_chat_template_goldens.py)");
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(tr->as_string()) == got,
            "golden tokenizer revision does not match this tokenizer.json");
  }

  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const dgpp::minijson::Value* name = rec.find("name");
    const dgpp::minijson::Value* kwargs = rec.find("kwargs");
    const dgpp::minijson::Value* render = rec.find("render");
    const dgpp::minijson::Value* ids = rec.find("ids");
    require(name && kwargs && render && ids, "malformed corpus line");
    const std::string rendered =
        [&] {
          try {
            return tpl.render(dgpp::glm::Value::from_minijson(*kwargs));
          } catch (const std::exception& e) {
            throw std::runtime_error("case '" + std::string(name->as_string()) +
                                     "': " + e.what());
          }
        }();
    const std::string want(render->as_string());
    if (rendered != want) {
      // Show the first divergence (byte offset + context) — these
      // failures are the whole point of the gate.
      size_t off = 0;
      while (off < rendered.size() && off < want.size() &&
             rendered[off] == want[off])
        ++off;
      require(false, "case '" + std::string(name->as_string()) +
                         "' diverges at byte " + std::to_string(off) +
                         ": expected " + want.substr(off < 12 ? 0 : off - 12, 24) +
                         ", got " + rendered.substr(off < 12 ? 0 : off - 12, 24));
    }
    const std::vector<int64_t> got_ids =
        tok.encode(std::string_view(render->as_string()));
    std::vector<int64_t> want_ids;
    for (const auto& v : ids->items()) want_ids.push_back(v.as_int(-1));
    require(got_ids == want_ids,
            "case '" + std::string(name->as_string()) +
                "': tokenizer ids diverge (" + std::to_string(got_ids.size()) +
                " vs " + std::to_string(want_ids.size()) + ")");
    ++checked;
  }
  DGPP_LOG_INFO("glm_chat_template_test: {}/{} cases exact (render + ids)",
                checked, lines.size() - 1);

  // The refusal contract: unsupported constructs must fail at compile
  // time, naming the construct. ({% break %} is checked at render time —
  // a top-level break only errors when executed, like Jinja.)
  struct BadCase {
    const char* source;
    std::string needle;
    bool render_too;  // also render with dummy globals and expect the needle
  };
  const BadCase bad[] = {
      {"{% do x = 1 %}", "do", false},
      {"{% include 'x' %}", "include", false},
      {"{{ x | join(',') }}", "join", false},
      {"{{ x is number }}", "number", false},
      {"{% if x %}{% endfor %}", "endfor", false},
      {"{% set a, b = 1, 2 %}", "tuple", false},
      {"{% macro m(a=1) %}{% endmacro %}", "default parameter", false},
      {"{% for x in y %}{% endfor %}{% break %}", "break", true},
  };
  for (const BadCase& c : bad) {
    bool threw = false;
    std::string msg;
    try {
      const auto t = dgpp::glm::ChatTemplate::compile(c.source);
      if (c.render_too) {
        dgpp::glm::Value::Members g;
        g.emplace_back("y", dgpp::glm::Value::list_value({}));
        (void)t.render(dgpp::glm::Value::map_value(std::move(g)));
      }
    } catch (const std::exception& e) {
      threw = true;
      msg = e.what();
    }
    require(threw && msg.find(c.needle) != std::string::npos,
            "expected a loud refusal naming '" + c.needle + "', got: " + msg);
  }

  // A missing template file refuses; an empty source refuses.
  bool threw = false;
  try {
    (void)dgpp::glm::ChatTemplate::load("/nonexistent/chat_template.jinja");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "load of a missing file must throw");
  threw = false;
  try {
    (void)dgpp::glm::ChatTemplate::compile("");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "empty source must refuse");
}


// Structural JSON equality: kinds must match (3 and 3.0 differ, as they do
// on the wire), arrays elementwise, objects member-wise in order.
bool json_equal(const dgpp::minijson::Value& a, const dgpp::minijson::Value& b) {
  using K = dgpp::minijson::Value::Kind;
  if (a.kind() != b.kind()) return false;
  switch (a.kind()) {
    case K::Null: return true;
    case K::Bool: return a.as_bool() == b.as_bool();
    case K::Int: return a.as_int() == b.as_int();
    case K::Double: return a.as_double() == b.as_double();
    case K::String: return a.as_string() == b.as_string();
    case K::Array: {
      if (a.items().size() != b.items().size()) return false;
      for (size_t i = 0; i < a.items().size(); ++i)
        if (!json_equal(a.items()[i], b.items()[i])) return false;
      return true;
    }
    case K::Object: {
      if (a.members().size() != b.members().size()) return false;
      for (size_t i = 0; i < a.members().size(); ++i)
        if (a.members()[i].key != b.members()[i].key ||
            !json_equal(a.members()[i].value, b.members()[i].value))
          return false;
      return true;
    }
  }
  return false;
}

// M6 6f: the template's rendering of an assistant tool-call message IS
// the model's output format, so render → encode → parse must round-trip
// over every golden case that carries one: the parser (the real
// tokenizer's markers and decode, the case's tool schemas) must recover
// each call's name and arguments exactly.
DGPP_TEST(glm_tool_call_render_encode_parse_roundTrip) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  const std::string model_id =
      env_model && *env_model ? env_model : "unsloth/GLM-5.3-Flash-FP8";
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::glm::ChatTemplate tpl = dgpp::glm::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::GlmTokenizer tok = dgpp::GlmTokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::glm::ChatMarkers markers = dgpp::glm::ChatMarkers::from_tokenizer(tok);
  require(markers.reasoning_available() && markers.tool_calls_available(),
          "the tokenizer carries the template's markers");
  DGPP_LOG_INFO(
      "glm_chat_template_test: markers <think> {} </think> {} <tool_call> {} "
      "</tool_call> {} <arg_key> {}/{} <arg_value> {}/{}",
      markers.think_open.id, markers.think_close.id, markers.tool_call_open.id,
      markers.tool_call_close.id, markers.arg_key_open.id,
      markers.arg_key_close.id, markers.arg_value_open.id,
      markers.arg_value_close.id);
  const std::vector<int64_t> observation = tok.encode("<|observation|>");
  require(observation.size() == 1, "<|observation|> is one added token");

  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  size_t turns = 0, calls = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;

      // The assistant turn's text: the render through message k minus the
      // render through message k-1 (no generation prompt on either).
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::glm::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::glm::Value::from_minijson(messages.items()[j]));
        dgpp::glm::Value::Members g;
        g.emplace_back("messages", dgpp::glm::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::glm::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::glm::Value::boolean(false));
        return tpl.render(dgpp::glm::Value::map_value(std::move(g)));
      };
      const std::string before = render_through(k);
      const std::string through = render_through(k + 1);
      require(through.compare(0, before.size(), before) == 0,
              name + ": the render grows by the assistant turn");
      std::string turn = through.substr(before.size());
      const std::string kAssistant = "<|assistant|>";
      require(turn.compare(0, kAssistant.size(), kAssistant) == 0,
              name + ": the turn opens with <|assistant|>: " + turn);
      turn.erase(0, kAssistant.size());

      // The model's ids for that turn, EOS appended; parsed as the service
      // parses them (the prompt ended in <think>).
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(observation[0]);
      dgpp::glm::ToolCallParser::Options opts;
      opts.start_in_reasoning = true;
      dgpp::glm::ToolCallParser parser(
          markers,
          [&](const std::vector<int64_t>& v) { return tok.decode(v, true); },
          tools ? dgpp::glm::ToolSchemas(*tools) : dgpp::glm::ToolSchemas(),
          opts);
      std::vector<dgpp::glm::ToolCallParser::Event> events;
      for (const int64_t id : ids) parser.feed(id, &events);
      parser.finish(&events);
      std::string reasoning, content;
      std::vector<dgpp::glm::ToolCallParser::Call> got;
      for (const auto& ev : events) {
        using Kind = dgpp::glm::ToolCallParser::Event::Kind;
        if (ev.kind == Kind::kReasoning) reasoning += ev.text;
        if (ev.kind == Kind::kContent) content += ev.text;
        if (ev.kind == Kind::kToolCall) got.push_back(ev.call);
      }
      require(reasoning.empty() && content.empty(),
              name + ": a tool-call turn has no text (got reasoning '" +
                  reasoning + "', content '" + content + "')");
      require(got.size() == tcs->items().size(),
              name + ": " + std::to_string(got.size()) + " calls parsed, " +
                  std::to_string(tcs->items().size()) + " expected");
      for (size_t c = 0; c < got.size(); ++c) {
        const dgpp::minijson::Value& tc = tcs->items()[c];
        const dgpp::minijson::Value* fn = tc.find("function");
        const dgpp::minijson::Value& def = fn ? *fn : tc;
        require(got[c].name == def.at("name").as_string(),
                name + ": call " + std::to_string(c) + " name '" + got[c].name +
                    "' != '" + std::string(def.at("name").as_string()) + "'");
        const dgpp::minijson::ParseResult args = dgpp::minijson::parse(got[c].arguments);
        require(json_equal(args.root, def.at("arguments")),
                name + ": call " + std::to_string(c) + " arguments " +
                    got[c].arguments + " differ from the case's");
        ++calls;
      }
      ++turns;
    }
  }
  require(turns >= 6 && calls >= 9,
          "expected at least 6 tool-call turns / 9 calls in the corpus, got " +
              std::to_string(turns) + " / " + std::to_string(calls));
  DGPP_LOG_INFO("glm_chat_template_test: {} tool-call turns ({} calls) round-trip "
                "render -> encode -> parse exactly",
                turns, calls);
}

}  // namespace

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return ::dgpp::test::run_all();
}
