#pragma once
// Shard descriptor: a precomputed plan over a sharded safetensors checkpoint.
// Generated by tools/make_shardspec.py (offline, cold path); consumed here to
// bind mmaps and locate tensors by logical name without re-parsing headers.
#include <filesystem>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "loaders/safetensors.hpp"

namespace dgpp {

struct ShardInfo {
  std::string filename;
  uint64_t size_bytes = 0;
};

struct SpecTensor {
  uint32_t shard = 0;
  DType dtype{};
  std::vector<int64_t> shape;
  std::string role;
  uint64_t nbytes = 0;
};

class ShardedCheckpoint {
 public:
  struct Config {
    std::string dir;             // checkpoint root directory
    std::string spec_path;       // shardspec.json path
    bool eager_bind = true;      // open all shard mmaps at construction
  };

  explicit ShardedCheckpoint(const Config& c);

  const std::string& model_id() const { return model_id_; }
  size_t shard_count() const { return shards_.size(); }
  const std::vector<ShardInfo>& shards() const { return shards_; }
  const SpecTensor* find(std::string_view name) const;
  const std::vector<std::pair<std::string, SpecTensor>>& tensors() const {
    return tensor_list_;
  }

  // Binds concrete mmap; throws if tensor missing or dtype mismatches spec.
  const void* tensor_data(std::string_view name, DType expect_dtype,
                          std::initializer_list<int64_t> expect_shape) const;

 private:
  void bind_all();

  Config cfg_;
  std::string model_id_;
  std::vector<ShardInfo> shards_;
  std::vector<std::unique_ptr<SafetensorsFile>> bound_;
  std::unordered_map<std::string_view, SpecTensor> by_name_;
  std::vector<std::pair<std::string, SpecTensor>> tensor_list_;
};

}  // namespace dgpp
