# The version stamp (2026-09-06, the productionizing pass): run at every
# build (a custom target), it writes dgpp_version.hpp only when its content
# changes, so a new commit re-stamps the binary without a reconfigure and
# an unchanged tree does not relink.
#
#   -DSOURCE_DIR=<repo> -DOUT=<path/dgpp_version.hpp> -DBASE_VERSION=<x.y.z>
#
# The version is "<base>+g<sha12>" and "<base>+g<sha12>.dirty" when the
# tree has uncommitted changes; without git it is "<base>+unknown".
find_package(Git QUIET)
set(_sha "unknown")
set(_dirty "")
if(GIT_FOUND)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
                  OUTPUT_VARIABLE _sha OUTPUT_STRIP_TRAILING_WHITESPACE
                  RESULT_VARIABLE _rc ERROR_QUIET)
  if(NOT _rc EQUAL 0)
    set(_sha "unknown")
  else()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
                    OUTPUT_VARIABLE _status OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT "${_status}" STREQUAL "")
      set(_dirty ".dirty")
    endif()
  endif()
endif()
if(_sha STREQUAL "unknown")
  set(_version "${BASE_VERSION}+unknown")
else()
  set(_version "${BASE_VERSION}+g${_sha}${_dirty}")
endif()
file(WRITE "${OUT}.tmp"
"// Generated by cmake/version.cmake at build time; do not edit.
#pragma once
#define DGPP_VERSION \"${_version}\"
#define DGPP_GIT_SHA \"${_sha}\"
#define DGPP_BASE_VERSION \"${BASE_VERSION}\"
")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
